### ISSUE TITLE
[epic] Flowershow CLI v1

### ISSUE THREAD

**Issue by rufuspollock** [datopian/flowershow#19]
Creating a command line interface for flowershow.

## Questions

* [ ] Use typescript for this as a first tryout? **✅2022-07-01 yes**

## Acceptance

* [ ] Have a chosen a framework (shortlist: commander, oclif, arg - but this seems a bit too basic?)
* [ ] `npx flowershow` or simple `flowershow` (if i have globally installed flowershow) command works and prints out basic help message (if no args etc)

## Tasks

* [x] Create `packages/flowershow`
* [x] #134 
* [ ] CLI v0.2 add a preview / show command
* [ ] CLI v0.3 add a build command

### What do i want to do from command line or otherwise

Simplest thing: get into a directory and do flowershow dev/show and i get a running local preview

```
mkdir test
touch test/README.md
cd test
flowershow show

...

http://localhost:3000/ # browser automatically opened
```

Other functions

```
flowershow init
flowershow publish
```

**Comment by rufuspollock** [comment]
@airtonix good point and done https://www.npmjs.com/package/flowershow

**Comment by rufuspollock** [comment]
Add v0.1, v0.2, v0.3 parts of CLI

**Comment by danielo515** [comment]
Can you please clarify if the CLI is deprecated or not? It is very confusing
