### ISSUE TITLE
Analytics other than Google Analytics (and switch to pliny model)

### ISSUE THREAD

**Issue by rufuspollock** [datopian/flowershow#238]
Suggest we support broader set of providers e.g. plausible, simpleanalytics etc.

Easiest way would be to adopt the relevant pliny module: https://github.com/timlrx/pliny/tree/main/packages/pliny/src/analytics (which also supports google analytics). 

## Acceptance
- [x] Add `analytics` component to `@portaljs/core` ** ✅18/1/2024 https://github.com/datopian/portaljs/commit/96904aef0dedff6ae38a98f185ab33f78cbd7603 **
- [x] Add `analytics` component from `@portaljs/core` to `flowershow` ** ✅18/1/2024 https://github.com/datopian/flowershow/pull/614/commits/6c07b78c1b02f59a391d6134c975786d37da92b5 **
- [x] Update documentation ** ✅19/1/2024 https://github.com/datopian/flowershow-app/commit/a3b699d30a6a54329d3bcf72feefd056b4a3a219 **

**Comment by rufuspollock** [comment]
@mohamedsalem401 this is a good one for you - please take a look.

**Comment by mohamedsalem401** [comment]
FIXED. Now FlowerShow supports Google Analytics, Plausible, PostHog, Simple Analytics, and Umami.
