### ISSUE TITLE
Improve self-publishing experience - self-publishing v0.2

### ISSUE THREAD

**Issue by rufuspollock** [datopian/flowershow#352]
Improve the self-publishing experience. Specifically:

- Simpler (less choice)
- Faster

Here are some ideas

- [ ] don't have to worry where i put assets: can put my assets e.g. images, data etc anywhere and automatically moved to public as appropriate
- [ ] don't have to worry about content directory: can put my markdown wherever https://github.com/flowershow/flowershow/discussions/323 **💬 we can do this today if you don't install flowershow into the content directory**
- [ ] faster install (and install the latest): don't have to install flowershow for each project - have one central flowershow installation
- [x] Install without assets folder #207 
- [ ] Install is maybe wrong name - better would be `init` or similar like that as what we are really doing is "initializing" a flowershow based site.
  - install could be reserved for actually installing in future we have a pure flowershow install (e.g. that puts flowershow somewhere common)
- [ ] #273 
- [ ] don't require users to put config.js and getters into their content folder (see this discussion #423)

## Notes

See install teardown on 2022-12-09: https://flowershow.app/journal/2022-12-09

**Comment by rufuspollock** [comment]
FIXED. WONTFIX. We didn't do things listed here ... because we didn't something even better to improve self-publishing #509 and #522  i.e.

- obsidian plugin
- plus repo that is a template ...
