### ISSUE TITLE
Tutorial: Use Flowershow as a NextJS template

### ISSUE THREAD

**Issue by rufuspollock** [datopian/flowershow#396]
use Flowershow as a straight-up NextJS template. It's open-source, batteries-included and well supported. 

Imagine a title like: "Jumpstart a NextJS site with contentlayer support and tailwind using flowershow"

Definitely something to post on dev.to etc.

Could be video or text or both (make the script and publish that and make the video).

Note: prior to releasing this probably want to do #307 and emphasize option of just using to publish markdown

## Status

Link to draft: https://hackmd.io/LuIu_c_QRsSxR6s92NSoJg?both

## Acceptance

Topics to cover

- [x] Intro: what and why
  - [x] what is the niche: publishing a markdown driven site - could be a blog, docs, etc. *not* a generic nextjs template. more if you want nextjs for a content website. Get a jumpstart on that.
  - [x] What features does Flowershow have (i.e. how does this help you) e.g. blog, theming, clean separate of content from theme. Contentlayer and tailwind out of the box etc. Power of MDX
- [x] Screenshots of what we've built ourselves using it showing the flexibility e.g. one or more of Flowershow, Datopian.com, DataHub.io, LifeItself
- [x] Howto (create your site)
  - [x] install and use
  - [x] basic configuration with config.js
  - [x] use of MDX and our special support to make accessing data easy (getters stuff) **add blog showing this**

## Tasks

- [x] look at some similar tutorials on dev.to etc.
- [x] emphasize this is good for content driven website
- [x] mention important features
- [x] basic configuration with config.js etc
- [x] use of MDX and our special support to make accessing data easy (getters stuff)
- [ ] post to
  - [ ] Dev.to
  - [x] Reddit **2023/02/21 [link](https://www.reddit.com/r/nextjs/comments/1180z1d/jumpstart_a_contentdriven_nextjs_site_with/?utm_source=share&utm_medium=web2x&context=3)
- [ ] announced on our Discord channel

**Comment by rufuspollock** [comment]
@PhilippeduPreez i've just bumped this up as you are making such good progress. If you don't have time we'll just roll this to the next sprint.

**Comment by olayway** [comment]
@PhilippeduPreez I've added a link to your draft in the description. I've also copied over acceptance criteria and tasks into it, so it's easier to compare them against the content. I've also changed the content itself a bit, but only in part, and added comments. Please create a PR with the second version :)

**Comment by olayway** [comment]
@PhilippeduPreez reopening this so that we don't forget about announcing our awesome tutorial to the world! 😃

**Comment by olayway** [comment]
Also: please add a link to it on our docs index page.

**Comment by PhilippeduPreez** [comment]
@khalilcodes @olayway Can I be added as a member to Flowershow on dev.to so I can make a post from there? :)

**Comment by olayway** [comment]
@rufuspollock ^^^

**Comment by rufuspollock** [comment]
FIXED. This was done. For now we won't post on dev.to.
