### ISSUE TITLE
[epic] Switch content layer to markdowndb (from contentlayer.dev)

### ISSUE THREAD

**Issue by rufuspollock** [datopian/flowershow#465]
We want to replace contentlayer.dev with our markdowndb for the content/data layer of Flowershow apps.

## Acceptance

- [x] MarkdownDB package with current markdowndb code
  - [x] MarkdownDB package in `packages` with a README
  - [x] Code with tests copied there from DataHub 
- [x] #471
- [x] #481
- [ ] ...

**Comment by olayway** [comment]
Closing as completed with #483.
