### ISSUE TITLE
Documentation updates

### ISSUE THREAD

**Issue by olayway** [datopian/flowershow#484]
## User story

As a user, I want to be able to find comprehensive and up-to-date documentation of a given feature. Specifically after the switch from `contentlayer` to our `@flowershow/markdowndb` package.

## Acceptance
- [ ] all docs pages are up-to-date
- [ ] every feature has a doc page
- [ ] every doc page is listed on the `docs/index.md` page

## Tasks
- [ ] `docs/config` page has a full list of all available config options with a short description (if not super clear) 
- [ ] ...

**Comment by rufuspollock** [comment]
@olayway i would definitely consider markdowndb is Flowershow v2-alpha or something. We could even have 2 sites e.g. v1.flowershow.app that runs v1 branch (we could branch v1) and a v2 which is main ... (cf how tailwind etc does it). However, this could be overkill given where we are in terms of usage etc atm.
