### ISSUE TITLE
Turn this repo into core template and move core lib to portaljs repo

### ISSUE THREAD

**Issue by rufuspollock** [datopian/flowershow#509]
Why: turning this into the simple template (and having core lib) elsewhere makes it simpler for users who just have one obvious repo to use or clone.

Why move core lib: because core lib is used in portaljs and has a lot of overlap. Given overlap easier to maintain in one place.

## Acceptance

- [x] Move all the core Flowershow code into github.com/datopian/portaljs **🚧2023-06-06  in https://github.com/datopian/portaljs/pull/923**
- [ ] Turn github.com/datopian/flowershow into the template people can "just use" i.e. the template
  - [ ] This template uses the core library now in portaljs

## Tasks

- [x] Remove CLI => just use obsidian plugin or use the template 🔥
  - [ ] install: will just clone or fork this repo
  - [ ] What about preview in future? people using preview can just clone and use nextjs tooling
- [x] `packages` to portaljs
  - [x] core package => move over wholesale
  - [x] remark stuff all moves across no problem
  - [x] cli removed (see above)
  - [x] markdowndb => delete 🔥
  - [ ] Need to publish under the new scope
- [x] `examples`: remove as out of date
  - [x] check if any blogs refer to these and remove references
- [x] e2e `tests`: move to portaljs
  - [x] Investigate if that can work easily **the easiest thing I can think of is adding the template as a submodule, but probably can be solved without it; for now just moved it to datopian/flowershow-template-e2e, will adjust later**
- [x] Move `flowershow-template` to root of `flowershow`
  - [ ] Deprecate flowershow-template i.e. add notice
  - [ ] Update references in other places
  - [ ] Make `flowershow` into a github template

## Questions

- [x] What about changesets changelog? **✅2023-06-06 lose them because will break in new location? and we've already removed. Basic rule: do the simplest thing possible.**
- [ ] What about package versions? **I thought the best option is to even them all out to 1.0.0, create git tags with this version for each new package, and start from there, since we're going to publish under the new scope and there won't be corresponding tags in portal js repo so it makes no sense to keep the original onces**

**Comment by olayway** [comment]
@rufuspollock do we want to move all remark stuff to portaljs repo as well? Maybe we should move all these packages to datopian org as separate repos instead?

**Comment by rufuspollock** [comment]
@olayway estimates 2-4h left! (Did a bunch yesterday)

**Comment by rufuspollock** [comment]
FIXED. Summary:

- all the flowershow packages moved to portaljs repo, published under `@portaljs` scope, and `@flowershow` ones are deprecated
- `@flowershow/markdowndb` package deprecated and now published under `mddb`
- flowershow template, portaljs site, portaljs example projects and markdowndb examples updated to account for the above changes
- datopian/flowershow repo is now the template repo
  - `datopian/flowershow-template` is archived
  - `obsidian-flowershow` and the CLI updated accordingly
- `datopian/flowershow-cli` created for now as I have no idea how much time it will take to get the obsidian plugin pubished and people seem to be using it and e.g. had to update path to the current template repo **💬2023-06-16 why do we need the cli anymore? - don't you just fork the template?** ⏭️ Create dedicated issue to analyse and implement
- E2E tests setup in `datopian/flowershow-template-e2e` - can be run locally and are also run in the Flowershow template's CI
