### ISSUE TITLE
Setup E2E tests after converting this repo to Flowershow's template repo

### ISSUE THREAD

**Issue by olayway** [datopian/flowershow#521]
## Acceptance
- our old E2E Playwright tests are executed on each push to `main` and each PR against `main`
- they live in a separate repo: https://github.com/datopian/flowershow-template-e2e
- they can be run locally as well
- they have README with instructions on how to use them locally and in the CI
- all the tests pass

```[tasklist]
### Tasks
- [x] adjust [the e2e repo](https://github.com/datopian/flowershow-template-e2e) and its setup script to allow for local testing
- [x] add README to [the e2e repo](https://github.com/datopian/flowershow-template-e2e) with instructions
- [x] create E2E workflow in this repo
```

**Comment by olayway** [comment]
All done
