### ISSUE TITLE
Make this a github template repo (even though it had lfs files at some point)

### ISSUE THREAD

**Issue by rufuspollock** [datopian/flowershow#523]
We want it to be easy to clone this repo as a template so that people can use from obsidian plugin etc.

This requires purging git lfs from our history

## Tasks

- [x] Push a current up to date clone of this repo to e.g. flowershow-archive-2023-06-19 **✅2023-10-31 have a no lfs backup at https://github.com/rufuspollock/flowershow-no-lfs**
- [x] Force push HEAD (i.e. current without git lfs) to datopian/flowershow **✅2023-10-31 ❌ this does not fix the problem - see discussion in comments**
- [x] Email github support **✅2023-11-06 got the answer (see last comment) that what we want is not possible. Once you once had lfs files in your repo you can never go back!**
- [x] .... **✅2023-11-06 ❌**

**Comment by rufuspollock** [comment]
Had a try today and other less destructive options e.g.

```
git lfs migrate export --everything --include="*"
```

And force pushing ... but no luck.

Note that just pushing head did work ...

**Comment by rufuspollock** [comment]
@davidgasquez any ideas how to fix this 😄

**Comment by davidgasquez** [comment]
Woah, no clue to be honest. Mind sharing some extra context on the error you're facing? Happy to dig a bit and explore the error/issue.

**Comment by olayway** [comment]
@davidgasquez I think I just fixed this! Wanted to give you some context and paste the error Rufus was getting with `git lfs migrate export` but it just worked for me :)

**Comment by davidgasquez** [comment]
Sweet! The good ol "trying again the same stuff until it works". :joy:

**Comment by rufuspollock** [comment]
@olayway i'd tried exactly this process with a fork of the repo and had the same experience - the checkmark still can't be ticked. (that was what i meant by "no luck").

BTW i'd recommend we try all this out on a **fork** before we change this repo - we don't want to accidentally lose stuff ... ( was working with a fork for all of this).

**Comment by rufuspollock** [comment]
OK, i've even tried force pushing a clean head branch (no lfs at all) to a fork of this repo and ... you still have the greyed out button. My guess is there are still files in github's lfs file storage. If you look at this page https://docs.github.com/en/repositories/working-with-files/managing-large-files/removing-files-from-git-large-file-storage

> After you remove files from Git LFS, the Git LFS objects still exist on the remote storage and will continue to count toward your Git LFS storage quota.
> 
> To remove Git LFS objects from a repository, delete and recreate the repository. When you delete a repository, any associated issues, stars, and forks are also deleted. For more information, see "[Deleting a repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/deleting-a-repository)." If you need to purge a removed object and you are unable to delete the repository, please [contact support](https://docs.github.com/en/support) for help.

I'm going to now try and contact support to get files purged from this repo.

**Comment by rufuspollock** [comment]
NB: i've confirmed that running:

```
git lfs migrate export --everything --include="*"
```

And pushing to a **clean** repo (not a fork) works - i.e. template option is available.

## Message to github support

Hi,

We want to turn our repository https://github.com/datopian/flowershow into a template repository.

However, we currently have the option greyed out:

![image.png](https://github.zendesk.com/attachments/token/xlSsyInYg80OJDodKZPde8Dzx/?name=image.png)

This is true even though we have now purged all lfs files from the repo.

We suspect there is something at github's end that needs to happen, perhaps (?) removing all Git LFS storage files associated https://github.com/datopian/flowershow (we are happy for you to do this!)

We have this suspicion following instructions in https://docs.github.com/en/repositories/working-with-files/managing-large-files/removing-files-from-git-large-file-storage

> To remove Git LFS objects from a repository, delete and recreate the repository. When you delete a repository, any associated issues, stars, and forks are also deleted. For more information, see "Deleting a repository." **If you need to purge a removed object and you are unable to delete the repository, please contact support for help.** [emphasis added]

Best,

Rufus Pollock

## Background

More info in: https://github.com/datopian/flowershow/issues/523

We want to turn our repository https://github.com/datopian/flowershow into a template repository.

That requires removing all git lfs files.

We've done this running git lfs export etc and force pushing. However, the "make template repository" is still greyed out:

![image.png](https://github.zendesk.com/attachments/token/xlSsyInYg80OJDodKZPde8Dzx/?name=image.png)

We've even tried force-pushing a clean "HEAD" of the repo (to a trial fork) and that did not work either.

What *does* work is:

1. cloning the repo
2. Running `git lfs migrate export --everything --include="*"`
3. Pushing to a new clean repo (not a fork)
4. At this point the option to make a template repo is available

This makes us suspect that there is something still around at the github end that indicates that datopian/flowershow is an "LFS" repo even though all lfs stuff is gone.

Reading the docs here:

https://docs.github.com/en/repositories/working-with-files/managing-large-files/removing-files-from-git-large-file-storage

We suspect we actually need to have the files purged from git lfs storage itself - which we are very happy to have happen (we only pushed a few asset files accidentally that we don't need anymore).

**Comment by rufuspollock** [comment]
OK. After various back and forth with github support got the final answer that this is not possible!

> Hi ...
>  
> Thanks for your patience while we've looked into this.
>  
> I'm afraid I don't have good news for you. It would take quite a lot of complex work on our back end to allow a repo that used to use LFS to become a template, and it's not likely that work is going to be prioritized any time soon, sorry!
>  
> If you want the repository at datopian/flowershow to be a template you'll need to delete and recreate it, which I know is not ideal.
>  
> As a compromise you could create a new repository to act as the template and have that automatically sync with datopian/flowershow to keep it up to date, and advertise its existence from the datopian/flowershow README? Our Marketplace [has a number of options for automatically mirroring repos](https://github.com/marketplace?category=&type=&verification=&query=mirror).
>  
> Sorry that's not the answer you were hoping for! Please let me know if you need any further help.
>  
> Cheers,

**Comment by rufuspollock** [comment]
WONTFIX. The options remaining are ...

- Have a separate repo as our template repo (original issue that people have 2 different places to go ...) - however could auto mirror
- Don't have a template repo
