### ISSUE TITLE
Current Roadmap link is to board in old org: is it up to date? Can we move it ...

### ISSUE THREAD

**Issue by davidgasquez** [datopian/flowershow#579]
Hey there! Seems that https://flowershow.app/docs/roadmap is pointing users to https://github.com/orgs/flowershow/projects/1/views/7. Curious if that's the current roadmap or is now living somewhere else. 

Might be also great to add a note in the https://github.com/flowershow org pointing to this repository. 

## Acceptance

- [ ] Move old project board (especially roadmap) to here (currently in old org)

## Tasks

- [ ] Figure out if we can recreate automatically **✅2023-10-26 ❌ not possible after many attempts and 500 errors ...**
- [ ] Create new project setup manually **✅2023-10-26 https://github.com/orgs/datopian/projects/45/views/5**
- [ ] Copy over items from old roadmap board https://github.com/orgs/flowershow/projects/1/views/7
- [ ] Update the instructions on https://flowershow.app/docs/roadmap to point to new board (Bonus: highlight the major things on our roadmap manually and point to the board for detail ...)

**Comment by davidgasquez** [comment]
This might be a worthy workaround: https://github.com/orgs/community/discussions/8548#discussioncomment-6169197

**Comment by rufuspollock** [comment]
> This might be a worthy workaround: https://github.com/orgs/community/discussions/8548#discussioncomment-6169197

Yes i tried that a few times and got 500 error every time.

Frankly, we could just recreate the roadmap by hand pretty quickly.

@davidgasquez would you like to have a go if i create the board itself ...

**Comment by davidgasquez** [comment]
Sure! They are... 12 issues (the others are in Done and don't think need to be moved)?

**Comment by rufuspollock** [comment]
@davidgasquez ok i've created a new board for you https://github.com/orgs/datopian/projects/45/views/5 and you can start migrating the roadmap over.

**Comment by rufuspollock** [comment]
FIXED. Updated link on main site and removed the old roadmap board.
