### ISSUE TITLE
How to edit a single page on a LifeItself website

### ISSUE THREAD

**Issue by olayway** [datopian/flowershow#589]
## Job story

As a new contributor to a Flowershow/PortalJS site (e.g. LifeItself.org), I want to edit an existing page on the website (whose contents are stored on GitHub), i.e. add/change some text, edit/add links to other pages, and/or add images to it so that the page is updated.

- What does this contributor know ...?
- Assume (but flag) you have edit access to the relevant repo/system (i.e. don't explain the process of getting the access in the tutorial)
- Any website that is markdown based with jam-stacky tendencies would be relevant here, not only Flowershow based one
- There is going to be a sandbox that readers can use when following the tutorial. A sandbox is a single instance of a simple Flowershow website with a few example pages. Assume this sandbox is already set up including automatic deployment.
- Will there be a live preview somewhere? No, not for now.
- ❗️ For now, add any terms/concepts explanations in e.g. Obsidian info callouts. They will form the basis of relevant sections in our Contributors Guide in the future.

## Tasks

- [x] Create a sandbox
**Repo: https://github.com/datopian/flowershow-sandbox; Deployment: https://flowershow-sandbox.vercel.app/**
- [x] Write a draft **https://hackmd.io/qAJFi0O0Q9G4ZubeSCet9g?edit**
- [ ] Write the content (no screenshots in this step yet)
- [ ] Try it out and adjust if necessary
- [ ] Improvements
    - [ ] Screenshots
    - [ ] Video (you have the script already with the tutorial)
